/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const XpAction = IDL.Variant({
  'RemixIdea' : IDL.Null,
  'ShareIdea' : IDL.Null,
  'ReceiveLike' : IDL.Null,
  'GenerateIdea' : IDL.Null,
});
export const CreateProjectInput = IDL.Record({
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'featureList' : IDL.Vec(IDL.Text),
});
export const ProjectId = IDL.Nat;
export const ProjectStatus = IDL.Variant({
  'deployed' : IDL.Null,
  'active' : IDL.Null,
  'draft' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'featureList' : IDL.Vec(IDL.Text),
});
export const AiFeatureSuggestion = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Nat,
});
export const CreatorLevel = IDL.Variant({
  'Dreamer' : IDL.Null,
  'Builder' : IDL.Null,
  'Legend' : IDL.Null,
  'Creator' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'totalXp' : IDL.Nat,
  'rank' : IDL.Nat,
  'ideasCount' : IDL.Nat,
  'level' : CreatorLevel,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalProjects' : IDL.Nat,
});
export const CreatorStats = IDL.Record({
  'streak' : IDL.Nat,
  'userId' : IDL.Principal,
  'totalXp' : IDL.Nat,
  'level' : CreatorLevel,
  'ideasGenerated' : IDL.Nat,
  'totalLikes' : IDL.Nat,
  'totalRemixes' : IDL.Nat,
});
export const PublicIdea = IDL.Record({
  'id' : IDL.Nat,
  'uniquenessScore' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'likeCount' : IDL.Nat,
  'remixCount' : IDL.Nat,
  'earningModel' : IDL.Text,
  'colorTheme' : IDL.Text,
  'appName' : IDL.Text,
  'createdAt' : Timestamp,
  'creatorId' : IDL.Principal,
  'description' : IDL.Text,
  'marketScore' : IDL.Nat,
  'creatorName' : IDL.Text,
  'viewCount' : IDL.Nat,
  'viralScore' : IDL.Nat,
  'successScore' : IDL.Nat,
  'category' : IDL.Text,
  'isPublic' : IDL.Bool,
  'monetizationScore' : IDL.Nat,
});
export const TemplateId = IDL.Nat;
export const Template = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'featureList' : IDL.Vec(IDL.Text),
});
export const PublishIdeaInput = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'earningModel' : IDL.Text,
  'colorTheme' : IDL.Text,
  'appName' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UpdateProjectInput = IDL.Record({
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'featureList' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'awardXpForAction' : IDL.Func([XpAction], [IDL.Nat], []),
  'createProject' : IDL.Func([CreateProjectInput], [Project], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'generate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ai' : IDL.Text,
          'trend' : IDL.Text,
          'lucky' : IDL.Text,
          'image' : IDL.Text,
        }),
      ],
      [],
    ),
  'getAiSuggestions' : IDL.Func(
      [ProjectId],
      [IDL.Vec(AiFeatureSuggestion)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfile], []),
  'getMyStats' : IDL.Func([], [CreatorStats], []),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getPublicIdea' : IDL.Func([IDL.Nat], [IDL.Opt(PublicIdea)], ['query']),
  'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
  'likeIdea' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listPublicIdeas' : IDL.Func(
      [
        IDL.Variant({
          'trending' : IDL.Null,
          'newest' : IDL.Null,
          'mostRemixed' : IDL.Null,
          'mostLiked' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [IDL.Vec(PublicIdea)],
      ['query'],
    ),
  'listTemplates' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Template)],
      ['query'],
    ),
  'publishIdea' : IDL.Func([PublishIdeaInput], [IDL.Nat], []),
  'remixIdea' : IDL.Func([IDL.Nat], [PublicIdea], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateProject' : IDL.Func([ProjectId, UpdateProjectInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const XpAction = IDL.Variant({
    'RemixIdea' : IDL.Null,
    'ShareIdea' : IDL.Null,
    'ReceiveLike' : IDL.Null,
    'GenerateIdea' : IDL.Null,
  });
  const CreateProjectInput = IDL.Record({
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'featureList' : IDL.Vec(IDL.Text),
  });
  const ProjectId = IDL.Nat;
  const ProjectStatus = IDL.Variant({
    'deployed' : IDL.Null,
    'active' : IDL.Null,
    'draft' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'featureList' : IDL.Vec(IDL.Text),
  });
  const AiFeatureSuggestion = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const CreatorLevel = IDL.Variant({
    'Dreamer' : IDL.Null,
    'Builder' : IDL.Null,
    'Legend' : IDL.Null,
    'Creator' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'totalXp' : IDL.Nat,
    'rank' : IDL.Nat,
    'ideasCount' : IDL.Nat,
    'level' : CreatorLevel,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'totalProjects' : IDL.Nat,
  });
  const CreatorStats = IDL.Record({
    'streak' : IDL.Nat,
    'userId' : IDL.Principal,
    'totalXp' : IDL.Nat,
    'level' : CreatorLevel,
    'ideasGenerated' : IDL.Nat,
    'totalLikes' : IDL.Nat,
    'totalRemixes' : IDL.Nat,
  });
  const PublicIdea = IDL.Record({
    'id' : IDL.Nat,
    'uniquenessScore' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'likeCount' : IDL.Nat,
    'remixCount' : IDL.Nat,
    'earningModel' : IDL.Text,
    'colorTheme' : IDL.Text,
    'appName' : IDL.Text,
    'createdAt' : Timestamp,
    'creatorId' : IDL.Principal,
    'description' : IDL.Text,
    'marketScore' : IDL.Nat,
    'creatorName' : IDL.Text,
    'viewCount' : IDL.Nat,
    'viralScore' : IDL.Nat,
    'successScore' : IDL.Nat,
    'category' : IDL.Text,
    'isPublic' : IDL.Bool,
    'monetizationScore' : IDL.Nat,
  });
  const TemplateId = IDL.Nat;
  const Template = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'featureList' : IDL.Vec(IDL.Text),
  });
  const PublishIdeaInput = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'earningModel' : IDL.Text,
    'colorTheme' : IDL.Text,
    'appName' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UpdateProjectInput = IDL.Record({
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'featureList' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'awardXpForAction' : IDL.Func([XpAction], [IDL.Nat], []),
    'createProject' : IDL.Func([CreateProjectInput], [Project], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'generate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ai' : IDL.Text,
            'trend' : IDL.Text,
            'lucky' : IDL.Text,
            'image' : IDL.Text,
          }),
        ],
        [],
      ),
    'getAiSuggestions' : IDL.Func(
        [ProjectId],
        [IDL.Vec(AiFeatureSuggestion)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfile], []),
    'getMyStats' : IDL.Func([], [CreatorStats], []),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getPublicIdea' : IDL.Func([IDL.Nat], [IDL.Opt(PublicIdea)], ['query']),
    'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
    'likeIdea' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listPublicIdeas' : IDL.Func(
        [
          IDL.Variant({
            'trending' : IDL.Null,
            'newest' : IDL.Null,
            'mostRemixed' : IDL.Null,
            'mostLiked' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [IDL.Vec(PublicIdea)],
        ['query'],
      ),
    'listTemplates' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Template)],
        ['query'],
      ),
    'publishIdea' : IDL.Func([PublishIdeaInput], [IDL.Nat], []),
    'remixIdea' : IDL.Func([IDL.Nat], [PublicIdea], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateProject' : IDL.Func([ProjectId, UpdateProjectInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };