/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiFeatureSuggestion {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'category' : string,
  'priority' : bigint,
}
export interface CreateProjectInput {
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'featureList' : Array<string>,
}
export type CreatorLevel = { 'Dreamer' : null } |
  { 'Builder' : null } |
  { 'Legend' : null } |
  { 'Creator' : null };
export interface CreatorStats {
  'streak' : bigint,
  'userId' : Principal,
  'totalXp' : bigint,
  'level' : CreatorLevel,
  'ideasGenerated' : bigint,
  'totalLikes' : bigint,
  'totalRemixes' : bigint,
}
export interface LeaderboardEntry {
  'displayName' : string,
  'userId' : Principal,
  'totalXp' : bigint,
  'rank' : bigint,
  'ideasCount' : bigint,
  'level' : CreatorLevel,
}
export interface Project {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : Timestamp,
  'featureList' : Array<string>,
}
export type ProjectId = bigint;
export type ProjectStatus = { 'deployed' : null } |
  { 'active' : null } |
  { 'draft' : null };
export interface PublicIdea {
  'id' : bigint,
  'uniquenessScore' : bigint,
  'features' : Array<string>,
  'likeCount' : bigint,
  'remixCount' : bigint,
  'earningModel' : string,
  'colorTheme' : string,
  'appName' : string,
  'createdAt' : Timestamp,
  'creatorId' : Principal,
  'description' : string,
  'marketScore' : bigint,
  'creatorName' : string,
  'viewCount' : bigint,
  'viralScore' : bigint,
  'successScore' : bigint,
  'category' : string,
  'isPublic' : boolean,
  'monetizationScore' : bigint,
}
export interface PublishIdeaInput {
  'features' : Array<string>,
  'earningModel' : string,
  'colorTheme' : string,
  'appName' : string,
  'description' : string,
  'category' : string,
}
export interface Template {
  'id' : TemplateId,
  'name' : string,
  'description' : string,
  'category' : string,
  'featureList' : Array<string>,
}
export type TemplateId = bigint;
export type Timestamp = bigint;
export interface UpdateProjectInput {
  'status' : ProjectStatus,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'featureList' : Array<string>,
}
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalProjects' : bigint,
}
export type XpAction = { 'RemixIdea' : null } |
  { 'ShareIdea' : null } |
  { 'ReceiveLike' : null } |
  { 'GenerateIdea' : null };
export interface _SERVICE {
  'awardXpForAction' : ActorMethod<[XpAction], bigint>,
  'createProject' : ActorMethod<[CreateProjectInput], Project>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'generate' : ActorMethod<
    [string, string],
    { 'ai' : string, 'trend' : string, 'lucky' : string, 'image' : string }
  >,
  'getAiSuggestions' : ActorMethod<[ProjectId], Array<AiFeatureSuggestion>>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getMyStats' : ActorMethod<[], CreatorStats>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getPublicIdea' : ActorMethod<[bigint], [] | [PublicIdea]>,
  'getTemplate' : ActorMethod<[TemplateId], [] | [Template]>,
  'incrementViewCount' : ActorMethod<[bigint], undefined>,
  'likeIdea' : ActorMethod<[bigint], bigint>,
  'listMyProjects' : ActorMethod<[], Array<Project>>,
  'listPublicIdeas' : ActorMethod<
    [
      { 'trending' : null } |
        { 'newest' : null } |
        { 'mostRemixed' : null } |
        { 'mostLiked' : null },
      [] | [string],
      bigint,
    ],
    Array<PublicIdea>
  >,
  'listTemplates' : ActorMethod<[[] | [string]], Array<Template>>,
  'publishIdea' : ActorMethod<[PublishIdeaInput], bigint>,
  'remixIdea' : ActorMethod<[bigint], PublicIdea>,
  'updateDisplayName' : ActorMethod<[string], boolean>,
  'updateProject' : ActorMethod<[ProjectId, UpdateProjectInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];