/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    displayName: string;
    userId: Principal;
    totalXp: bigint;
    rank: bigint;
    ideasCount: bigint;
    level: CreatorLevel;
}
export type Timestamp = bigint;
export interface CreatorStats {
    streak: bigint;
    userId: Principal;
    totalXp: bigint;
    level: CreatorLevel;
    ideasGenerated: bigint;
    totalLikes: bigint;
    totalRemixes: bigint;
}
export type TemplateId = bigint;
export interface Template {
    id: TemplateId;
    name: string;
    description: string;
    category: string;
    featureList: Array<string>;
}
export interface PublishIdeaInput {
    features: Array<string>;
    earningModel: string;
    colorTheme: string;
    appName: string;
    description: string;
    category: string;
}
export type UserId = Principal;
export interface PublicIdea {
    id: bigint;
    uniquenessScore: bigint;
    features: Array<string>;
    likeCount: bigint;
    remixCount: bigint;
    earningModel: string;
    colorTheme: string;
    appName: string;
    createdAt: Timestamp;
    creatorId: Principal;
    description: string;
    marketScore: bigint;
    creatorName: string;
    viewCount: bigint;
    viralScore: bigint;
    successScore: bigint;
    category: string;
    isPublic: boolean;
    monetizationScore: bigint;
}
export interface UpdateProjectInput {
    status: ProjectStatus;
    name: string;
    tags: Array<string>;
    description: string;
    featureList: Array<string>;
}
export interface AiFeatureSuggestion {
    id: bigint;
    title: string;
    description: string;
    category: string;
    priority: bigint;
}
export type ProjectId = bigint;
export interface CreateProjectInput {
    name: string;
    tags: Array<string>;
    description: string;
    featureList: Array<string>;
}
export interface Project {
    id: ProjectId;
    status: ProjectStatus;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    updatedAt: Timestamp;
    featureList: Array<string>;
}
export interface UserProfile {
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
    totalProjects: bigint;
}
export enum CreatorLevel {
    Dreamer = "Dreamer",
    Builder = "Builder",
    Legend = "Legend",
    Creator = "Creator"
}
export enum ProjectStatus {
    deployed = "deployed",
    active = "active",
    draft = "draft"
}
export enum Variant_trending_newest_mostRemixed_mostLiked {
    trending = "trending",
    newest = "newest",
    mostRemixed = "mostRemixed",
    mostLiked = "mostLiked"
}
export enum XpAction {
    RemixIdea = "RemixIdea",
    ShareIdea = "ShareIdea",
    ReceiveLike = "ReceiveLike",
    GenerateIdea = "GenerateIdea"
}
export interface backendInterface {
    awardXpForAction(action: XpAction): Promise<bigint>;
    createProject(input: CreateProjectInput): Promise<Project>;
    deleteProject(id: ProjectId): Promise<boolean>;
    generate(prompt: string, device: string): Promise<{
        ai: string;
        trend: string;
        lucky: string;
        image: string;
    }>;
    getAiSuggestions(projectId: ProjectId): Promise<Array<AiFeatureSuggestion>>;
    getLeaderboard(limit: bigint): Promise<Array<LeaderboardEntry>>;
    getMyProfile(): Promise<UserProfile>;
    getMyStats(): Promise<CreatorStats>;
    getProject(id: ProjectId): Promise<Project | null>;
    getPublicIdea(ideaId: bigint): Promise<PublicIdea | null>;
    getTemplate(id: TemplateId): Promise<Template | null>;
    incrementViewCount(ideaId: bigint): Promise<void>;
    likeIdea(ideaId: bigint): Promise<bigint>;
    listMyProjects(): Promise<Array<Project>>;
    listPublicIdeas(sort: Variant_trending_newest_mostRemixed_mostLiked, category: string | null, limit: bigint): Promise<Array<PublicIdea>>;
    listTemplates(category: string | null): Promise<Array<Template>>;
    publishIdea(input: PublishIdeaInput): Promise<bigint>;
    remixIdea(ideaId: bigint): Promise<PublicIdea>;
    updateDisplayName(name: string): Promise<boolean>;
    updateProject(id: ProjectId, input: UpdateProjectInput): Promise<boolean>;
}
import type { CreatorLevel as _CreatorLevel, CreatorStats as _CreatorStats, LeaderboardEntry as _LeaderboardEntry, Project as _Project, ProjectId as _ProjectId, ProjectStatus as _ProjectStatus, PublicIdea as _PublicIdea, Template as _Template, Timestamp as _Timestamp, UpdateProjectInput as _UpdateProjectInput, UserId as _UserId, XpAction as _XpAction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async awardXpForAction(arg0: XpAction): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.awardXpForAction(to_candid_XpAction_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardXpForAction(to_candid_XpAction_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProject(arg0: CreateProjectInput): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return from_candid_Project_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return from_candid_Project_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async generate(arg0: string, arg1: string): Promise<{
        ai: string;
        trend: string;
        lucky: string;
        image: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generate(arg0, arg1);
            return result;
        }
    }
    async getAiSuggestions(arg0: ProjectId): Promise<Array<AiFeatureSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiSuggestions(arg0);
            return result;
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getMyStats(): Promise<CreatorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return from_candid_CreatorStats_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return from_candid_CreatorStats_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicIdea(arg0: bigint): Promise<PublicIdea | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicIdea(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicIdea(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: TemplateId): Promise<Template | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async likeIdea(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.likeIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeIdea(arg0);
            return result;
        }
    }
    async listMyProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProjects();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProjects();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublicIdeas(arg0: Variant_trending_newest_mostRemixed_mostLiked, arg1: string | null, arg2: bigint): Promise<Array<PublicIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublicIdeas(to_candid_variant_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublicIdeas(to_candid_variant_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async listTemplates(arg0: string | null): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTemplates(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTemplates(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async publishIdea(arg0: PublishIdeaInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.publishIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishIdea(arg0);
            return result;
        }
    }
    async remixIdea(arg0: bigint): Promise<PublicIdea> {
        if (this.processError) {
            try {
                const result = await this.actor.remixIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.remixIdea(arg0);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: UpdateProjectInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectInput_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectInput_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CreatorLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorLevel): CreatorLevel {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CreatorStats_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorStats): CreatorStats {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicIdea]): PublicIdea | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Template]): Template | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: bigint;
    userId: Principal;
    totalXp: bigint;
    level: _CreatorLevel;
    ideasGenerated: bigint;
    totalLikes: bigint;
    totalRemixes: bigint;
}): {
    streak: bigint;
    userId: Principal;
    totalXp: bigint;
    level: CreatorLevel;
    ideasGenerated: bigint;
    totalLikes: bigint;
    totalRemixes: bigint;
} {
    return {
        streak: value.streak,
        userId: value.userId,
        totalXp: value.totalXp,
        level: from_candid_CreatorLevel_n10(_uploadFile, _downloadFile, value.level),
        ideasGenerated: value.ideasGenerated,
        totalLikes: value.totalLikes,
        totalRemixes: value.totalRemixes
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    updatedAt: _Timestamp;
    featureList: Array<string>;
}): {
    id: ProjectId;
    status: ProjectStatus;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    updatedAt: Timestamp;
    featureList: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n5(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        updatedAt: value.updatedAt,
        featureList: value.featureList
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    userId: Principal;
    totalXp: bigint;
    rank: bigint;
    ideasCount: bigint;
    level: _CreatorLevel;
}): {
    displayName: string;
    userId: Principal;
    totalXp: bigint;
    rank: bigint;
    ideasCount: bigint;
    level: CreatorLevel;
} {
    return {
        displayName: value.displayName,
        userId: value.userId,
        totalXp: value.totalXp,
        rank: value.rank,
        ideasCount: value.ideasCount,
        level: from_candid_CreatorLevel_n10(_uploadFile, _downloadFile, value.level)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Dreamer: null;
} | {
    Builder: null;
} | {
    Legend: null;
} | {
    Creator: null;
}): CreatorLevel {
    return "Dreamer" in value ? CreatorLevel.Dreamer : "Builder" in value ? CreatorLevel.Builder : "Legend" in value ? CreatorLevel.Legend : "Creator" in value ? CreatorLevel.Creator : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployed: null;
} | {
    active: null;
} | {
    draft: null;
}): ProjectStatus {
    return "deployed" in value ? ProjectStatus.deployed : "active" in value ? ProjectStatus.active : "draft" in value ? ProjectStatus.draft : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProjectInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProjectInput): _UpdateProjectInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_XpAction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: XpAction): _XpAction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProjectStatus;
    name: string;
    tags: Array<string>;
    description: string;
    featureList: Array<string>;
}): {
    status: _ProjectStatus;
    name: string;
    tags: Array<string>;
    description: string;
    featureList: Array<string>;
} {
    return {
        status: to_candid_ProjectStatus_n22(_uploadFile, _downloadFile, value.status),
        name: value.name,
        tags: value.tags,
        description: value.description,
        featureList: value.featureList
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_trending_newest_mostRemixed_mostLiked): {
    trending: null;
} | {
    newest: null;
} | {
    mostRemixed: null;
} | {
    mostLiked: null;
} {
    return value == Variant_trending_newest_mostRemixed_mostLiked.trending ? {
        trending: null
    } : value == Variant_trending_newest_mostRemixed_mostLiked.newest ? {
        newest: null
    } : value == Variant_trending_newest_mostRemixed_mostLiked.mostRemixed ? {
        mostRemixed: null
    } : value == Variant_trending_newest_mostRemixed_mostLiked.mostLiked ? {
        mostLiked: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: XpAction): {
    RemixIdea: null;
} | {
    ShareIdea: null;
} | {
    ReceiveLike: null;
} | {
    GenerateIdea: null;
} {
    return value == XpAction.RemixIdea ? {
        RemixIdea: null
    } : value == XpAction.ShareIdea ? {
        ShareIdea: null
    } : value == XpAction.ReceiveLike ? {
        ReceiveLike: null
    } : value == XpAction.GenerateIdea ? {
        GenerateIdea: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    deployed: null;
} | {
    active: null;
} | {
    draft: null;
} {
    return value == ProjectStatus.deployed ? {
        deployed: null
    } : value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
